## Create Array Using Python List

In [8]:
import numpy as np

# create a list named list1
list1 = [2, 4, 6, 8]

# create numpy array using list1
array1 = np.array(list1)

print(array1)

[2 4 6 8]


In [6]:
import numpy as np

# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


## Create an Array Using np.zeros()

In [11]:
import numpy as np

# create an array with 4 elements filled with zeros
array1 = np.zeros(4)

print(array1)

[0. 0. 0. 0.]


## Create an Array Using np.ones

In [32]:
arr_ones = np.ones((3, 3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Create N-D Array with a Specified Value

In [41]:
import numpy as np

# Create a 2-D array with elements initialized to 5 
numpy_array = np.full((2, 2), 5)

print("Array:", numpy_array)

Array: [[5 5]
 [5 5]]


## Create an Array With np.arange()
The np.arange() function returns an array with values within a specified interval.

In [14]:
import numpy as np

# create an array with values from 0 to 4
array1 = np.arange(5)

print("Using np.arange(5):", array1)

# create an array with values from 1 to 8 with a step of 2
array2 = np.arange(1, 9, 2)

print("Using np.arange(1, 9, 2):",array2)

Using np.arange(5): [0 1 2 3 4]
Using np.arange(1, 9, 2): [1 3 5 7]


## Create an Array With np.random.rand()
The np.random.rand() function is used to create an array of random numbers.

In [19]:
import numpy as np

# generate an array of 5 random numbers
array1 = np.random.rand(5)

print(array1)

[0.44958741 0.10792567 0.46073483 0.54398614 0.10470133]


## Create an Array With np.random.randint

In [35]:
arr_randint = np.random.randint(0, 10, size=(3, 3))
print(arr_randint)

[[9 5 5]
 [0 1 2]
 [2 9 5]]


## Create an Empty NumPy Array
To create an empty NumPy array, we use the np.empty() function

In [22]:
import numpy as np

# create an empty array of length 4
array1 = np.empty(4)

print(array1)

[0. 0. 0. 0.]


## Create arrays with a specific data type

In [26]:
arr_float = np.array([1.5, 2.4, 3.3, 4.2, 5.1], dtype=float)
print(arr_float)

[1.5 2.4 3.3 4.2 5.1]


## Array Functions

**NumPy provides many useful functions for working with arrays.** <br> For example, you can use the sum function to calculate the sum of all elements in an array:

In [30]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))

15
