# NumPy Input Output
NumPy offers input/output (I/O) functions for loading and saving data to and from

## Most Commonly Used I/O Functions

| Function | Description |
|----------|-------------|
| `save()` | Saves an array to a binary file in the NumPy .npy format |
| `load()` | Loads data from a binary file in the NumPy .npy format |
| `savetxt()` | Saves an array to a text file in a specific format |
| `loadtxt()` | Loads data from a text file |

## NumPy save() Function
In NumPy, the **save() function** is used to save an array to a binary file in the NumPy .npy format.

In [8]:
import numpy as np

# create a NumPy array
array1 = np.array([[1, 3, 5], 
                   [7, 9, 11]])

# save the array to a file
np.save('file1.npy', array1)

## NumPy load() Function


In [11]:
import numpy as np

# load the saved NumPy array
loaded_array = np.load('file1.npy')

# display the loaded array
print(loaded_array)

[[ 1  3  5]
 [ 7  9 11]]


## NumPy savetxt() Function
In NumPy, we use the **savetxt() function** to save an array to a text file.

In [14]:
import numpy as np

# create a NumPy array
array2 = np.array([[1, 3, 5], 
                   [7, 9, 11]])

# save the array to a file
np.savetxt('file2.txt', array2)

## NumPy loadtxt() Function

In [17]:
import numpy as np

# load the saved NumPy array
loaded_array = np.loadtxt('file2.txt')

# display the loaded array
print(loaded_array)

[[ 1.  3.  5.]
 [ 7.  9. 11.]]
