# NumPy Array Slicing
Array Slicing is the process of extracting a portion of an array. <br> With slicing, we can easily access elements in the array. It can be done on one or more dimensions of a NumPy array.

## Syntax of NumPy Array Slicing

## 1D NumPy Array Slicing
In NumPy, it's possible to access the portion of an array using the **slicing operator :**

In [54]:
import numpy as np

# create a 1D array 
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

# slice array1 from index 2 to index 6 (exclusive)
print(array1[2:6])  

# slice array1 from index 0 to index 8 (exclusive) with a step size of 2
print(array1[0:8:2])  

# slice array1 from index 3 up to the last element
print(array1[3:])  

# items from start to end
print(array1[:])   

[5 7 8 9]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]


## Modify Array Elements Using Slicing
With slicing, we can also modify array elements using:

1. start parameter
2. stop parameter
3. start and stop parameter
4. start, stop, and step parameter

### 1. Using start Parameter

In [57]:
import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from index 3 onwards
numbers[3:] = 20
print(numbers)

[ 2  4  6 20 20 20]


### 2. Using stop Parameter

In [59]:
import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify the first 3 elements
numbers[:3] = 40
print(numbers)


[40 40 40  8 10 12]


### 3. Using start and stop parameter

In [61]:
import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from indices 2 to 5
numbers[2:5] = 22
print(numbers)

[ 2  4 22 22 22 12]


### 4. Using start, stop, and step parameter

In [63]:
import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify every second element from indices 1 to 5
numbers[1:5:2] = 16
print(numbers)

[ 2 16  6 16 10 12]


## NumPy Array Negative Slicing
We can also use negative indices to perform negative slicing in NumPy arrays. <br> During negative slicing, elements are accessed from the end of the array.

In [65]:
import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# slice the last 3 elements of the array
# using the start parameter
print(numbers[-3:])    

# slice elements from 2nd-to-last to 4th-to-last element
# using the start and stop parameters
print(numbers[-5:-2])    

# slice every other element of the array from the end
# using the start, stop, and step parameters
print(numbers[-1::-2])  

[ 8 10 12]
[4 6 8]
[12  8  4]


## Reverse NumPy Array Using Negative Slicing
In NumPy, we can also reverse array elements using the negative slicing. For example,

In [30]:
import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# generate reversed array
reversed_numbers = numbers[::-1]
print(reversed_numbers)

# Here, the slice numbers[::-1] selects all the elements of the array with a step size of -1, which reverses the order of the elements.

[12 10  8  6  4  2]


# 2D NumPy Array Slicing
A 2D NumPy array can be thought of as a matrix, where each element has two indices, row index and column index.
<br>
To slice a 2D NumPy array, we can use the same syntax as for slicing a 1D NumPy array. 
<br>
The only difference is that we need to specify a slice for each dimension of the array.

## Syntax of 2D NumPy Array Slicing

In [40]:
# create a 2D array
array1 = np.array([[1, 3, 5, 7], 
                   [9, 11, 13, 15]])

print(array1[:2, :2])

#Here, the , in [:2, :2] separates the rows of the array.
#The first :2 returns first 2 rows i.e., entire array1 i.e [1,3]
#The second :2 returns first 2 columns from the 2 rows. i.e. [9, 11]

[[ 1  3]
 [ 9 11]]


## Example: 2D NumPy Array Slicing

In [43]:
import numpy as np

# create a 2D array 
array1 = np.array([[1, 3, 5, 7], 
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])


# slice the array to get the first two rows and columns
subarray1 = array1[:2, :2]

# slice the array to get the last two rows and columns
subarray2 = array1[1:3, 2:4]

# print the subarrays
print("First Two Rows and Columns: \n",subarray1)
print("Last two Rows and Columns: \n",subarray2)

First Two Rows and Columns: 
 [[ 1  3]
 [ 9 11]]
Last two Rows and Columns: 
 [[13 15]
 [ 6  8]]


# 3D NumPy Array Slicing

## Syntax of 3D NumPy Array Slicing

In [49]:
# create a 3D array
array1 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                   [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

print(array1[:2, :2, :2])


[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]]


### Example: 3D NumPy Array Slicing

In [52]:
import numpy as np

# create a 3D array 
array1 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                   [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])


# slice the array to get the first two rows, columns, and depth
subarray1 = array1[:2, :2, :2]

# slice the array to get the last two rows, columns, and depth
subarray2 = array1[1:3, 1:3, 1:3]

# print the subarrays
print("First Two Rows, Columns, and Depth: \n",subarray1)
print("Last two Rows, Columns, and Depth: \n",subarray2)

First Two Rows, Columns, and Depth: 
 [[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]]
Last two Rows, Columns, and Depth: 
 [[[14 15]
  [17 18]]

 [[23 24]
  [26 27]]]
