# **NumPy Array Reshaping**

# Introduction to NumPy Array Reshaping

NumPy array reshaping is the process of changing the shape of an array without modifying its data. In this, we will explore:

- The basics of NumPy array reshaping
- Syntax for reshaping arrays
- Examples of reshaping operations
- Common use cases for array reshaping

## Syntax

The syntax for NumPy array reshaping is as follows:

```python
np.reshape(array, newshape, order='C')

## Reshape 1D Array to 2D Array

In [16]:
import numpy as np

array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])
result = np.reshape(array1, (2, 4))
print(result)

#We can reshape this 1D array into a 2D array with 2 rows and 4 columns using the reshape() function

[[1 3 5 7]
 [2 4 6 8]]


## Reshape 1D Array to 3D Array

In [19]:
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])
result = np.reshape(array1, (2, 2, 2))
print(result)



[[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]


## Flatten N-d Array to 1-D Array
Flattening an array means converting a multidimensional array into a 1D array. <br> We can use the reshape() function with -1 as an argument to flatten an array.

In [23]:
array1 = np.array([[1, 3], [5, 7], [9, 11]])
result1 = np.reshape(array1, -1)
print(result1)

array2 = np.array([[[1, 3], [5, 7]], [[2, 4], [6, 8]]])
result2 = np.reshape(array2, -1)
print(result2)

[ 1  3  5  7  9 11]
[1 3 5 7 2 4 6 8]


## Example Use Cases
Here are some example use cases for NumPy array reshaping:
- Image processing: Reshaping an image array from 3D (height, width, channels) to 2D (height, width) for processing.
- Data analysis: Reshaping a dataset from 2D (rows, columns) to 1D (rows) for analysis.
- Machine learning: Reshaping input data from 1D to 2D or 3D for model training.