# **Joining and Splitting Arrays in NumPy**

### Creating Arrays

In [7]:
import numpy as np

# Create a 2D array
grid = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array
x = np.array([7, 8, 9])

# Create another 1D array
y = np.array([10, 11, 12])

## Concatenating Arrays
### Using np.concatenate

In [10]:
# Concatenate along the first axis (default)
concatenated = np.concatenate([grid, grid])
print(concatenated)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


### Using np.vstack and np.hstack

In [3]:
import numpy as np

# Create sample arrays
x = np.array([1, 2])
y = np.array([5, 6])
grid = np.array([[1, 2], [3, 4]])

print("Original arrays:")
print("x:", x)
print("y:", y)
print("grid:\n", grid)

# Vertically stack arrays
vstacked = np.vstack([x, grid])
print("\nVertically stacked:")
print(vstacked)

# Horizontally stack arrays
hstacked = np.hstack([grid, y[:, None]])
print("\nHorizontally stacked:")
print(hstacked)

Original arrays:
x: [1 2]
y: [5 6]
grid:
 [[1 2]
 [3 4]]

Vertically stacked:
[[1 2]
 [1 2]
 [3 4]]

Horizontally stacked:
[[1 2 5]
 [3 4 6]]


### Using np.dstack

In [18]:
# Stack arrays along the third axis
dstacked = np.dstack([grid, grid])
print(dstacked)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


## Splitting Arrays
### Using np.split

In [21]:
# Split an array at indices 3 and 5
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[7 8 9] [] []


### Using np.hsplit and np.vsplit

In [24]:
# Horizontally split an array at index 2
h1, h2 = np.hsplit(grid, [2])
print(h1, h2)

# Vertically split an array at index 1
v1, v2 = np.vsplit(grid, [1])
print(v1, v2)

[[1 2]
 [4 5]] [[3]
 [6]]
[[1 2 3]] [[4 5 6]]
