#  **Universal Functions (ufuncs)**

Universal functions (ufuncs) are a set of functions in NumPy that perform element-wise operations on arrays.

### What are ufuncs?

ufuncs are a set of functions that perform element-wise operations on arrays. They are called "universal" because they can operate on arrays with different shapes and sizes.

### Examples of ufuncs

Some examples of ufuncs include:

* `np.add`: performs element-wise addition
* `np.subtract`: performs element-wise subtraction
* `np.multiply`: performs element-wise multiplication
* `np.divide`: performs element-wise division
* `np.sin`: performs element-wise sine operation
* `np.cos`: performs element-wise cosine operation

In [5]:
import numpy as np

# MULTIPLY BY A SCALARS
nparr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nparr_esc = nparr * 10
print(nparr_esc)

[  0  10  20  30  40  50  60  70  80  90 100]


In [9]:
import numpy as np

# Define nparr
nparr = np.array([1, 2, 0, -1])

# ONE DIVIDED BY ZERO
nparr_one_div = 1/nparr
print(nparr_one_div)


[ 1.   0.5  inf -1. ]


C:\Users\Admin\AppData\Local\Temp\ipykernel_14796\3240388874.py:7: RuntimeWarning: divide by zero encountered in divide
  nparr_one_div = 1/nparr


In [9]:

# EXPONENT — ARRAYS — Squaring everything — Two options
np_arr_exp1 = nparr ** 2
print(np_arr_exp1)
np_arr_exp2 = np.square(nparr)
print(np_arr_exp2)


[  0   1   4   9  16  25  36  49  64  81 100]
[  0   1   4   9  16  25  36  49  64  81 100]


In [11]:

# SQUARE ROOT
nparr_sr = np.sqrt(nparr)
print(nparr_sr)



[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]


In [13]:
# EXPONENTIAL WITH ARRAYS
np_arr_exp3 = np.exp(nparr)
print(np_arr_exp3)



[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]


In [15]:
# MAX & MIN
nparr_max = np.max(nparr)
print(nparr_max)
nparr_min = np.min(nparr)
print(nparr_min)

10
0


In [17]:
# TRIGONOMETRIC
nparr_sin = np.sin(nparr)
print(nparr_sin)
nparr_cos = np.cos(nparr)
print(nparr_cos)
nparr_tan = np.tan(nparr)
print(nparr_tan)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566  0.64836083]


In [13]:
# INVERSE TRIGONOMETRIC
nparr_arcsin = np.arcsin(nparr)
print(nparr_arcsin)
nparr_arccos = np.arccos(nparr)
print(nparr_arccos)
nparr_arctan = np.arctan(nparr)
print(nparr_arctan)

[ 1.57079633         nan  0.         -1.57079633]
[0.                nan 1.57079633 3.14159265]
[ 0.78539816  1.10714872  0.         -0.78539816]


C:\Users\Admin\AppData\Local\Temp\ipykernel_14796\2973068308.py:8: RuntimeWarning: invalid value encountered in arcsin
  nparr_arcsin = np.arcsin(nparr)
C:\Users\Admin\AppData\Local\Temp\ipykernel_14796\2973068308.py:11: RuntimeWarning: invalid value encountered in arccos
  nparr_arccos = np.arccos(nparr)


In [21]:
# HYPERBOLIC
nparr_sinh = np.sinh(nparr)
print(nparr_sinh)
nparr_cosh = np.cosh(nparr)
print(nparr_cosh)
nparr_tanh = np.tanh(nparr)
print(nparr_tanh)

[0.00000000e+00 1.17520119e+00 3.62686041e+00 1.00178749e+01
 2.72899172e+01 7.42032106e+01 2.01713157e+02 5.48316123e+02
 1.49047883e+03 4.05154190e+03 1.10132329e+04]
[1.00000000e+00 1.54308063e+00 3.76219569e+00 1.00676620e+01
 2.73082328e+01 7.42099485e+01 2.01715636e+02 5.48317035e+02
 1.49047916e+03 4.05154203e+03 1.10132329e+04]
[0.         0.76159416 0.96402758 0.99505475 0.9993293  0.9999092
 0.99998771 0.99999834 0.99999977 0.99999997 1.        ]


In [23]:
# INVERSE HYPERBOLIC
nparr_arcsinh = np.arcsinh(nparr)
print(nparr_arcsinh)
nparr_arccosh = np.arccosh(nparr)
print(nparr_arccosh)
nparr_arctanh = np.arctanh(nparr)
print(nparr_arctanh)

[0.         0.88137359 1.44363548 1.81844646 2.09471255 2.31243834
 2.49177985 2.64412076 2.77647228 2.89344399 2.99822295]
[       nan 0.         1.3169579  1.76274717 2.06343707 2.29243167
 2.47788873 2.63391579 2.76865938 2.88727095 2.99322285]
[ 0. inf nan nan nan nan nan nan nan nan nan]


C:\Users\Admin\AppData\Local\Temp\ipykernel_24096\3703040605.py:4: RuntimeWarning: invalid value encountered in arccosh
  nparr_arccosh = np.arccosh(nparr)
C:\Users\Admin\AppData\Local\Temp\ipykernel_24096\3703040605.py:6: RuntimeWarning: divide by zero encountered in arctanh
  nparr_arctanh = np.arctanh(nparr)
C:\Users\Admin\AppData\Local\Temp\ipykernel_24096\3703040605.py:6: RuntimeWarning: invalid value encountered in arctanh
  nparr_arctanh = np.arctanh(nparr)


In [25]:
# STATISTICAL
nparr_mean = np.mean(nparr)
print(nparr_mean)
nparr_median = np.median(nparr)
print(nparr_median)
nparr_std = np.std(nparr)
print(nparr_std)
nparr_var = np.var(nparr)
print(nparr_var)

5.0
5.0
3.1622776601683795
10.0


In [27]:
# RANDOM NUMBER GENERATION
nparr_rand = np.random.rand(10)
print(nparr_rand)
nparr_randn = np.random.randn(10)
print(nparr_randn)
nparr_randint = np.random.randint(0, 10, 10)
print(nparr_randint)

[0.98832222 0.92401287 0.48715564 0.73804241 0.80750485 0.31910702
 0.16203072 0.91365402 0.58905883 0.86395622]
[-2.65218626  0.42419643 -0.61817287 -0.48897277  0.12755362 -0.58104188
 -0.54746594  1.14305102 -0.01089206  0.97231948]
[0 3 6 3 2 9 0 0 4 7]


In [18]:
import numpy as np

# Assuming nparr is defined as:
nparr = np.array([1, 2, 0, -1])

# LINEAR ALGEBRA
nparr_matmul = np.matmul(nparr[:, None], nparr[None, :])
print(nparr_matmul)

nparr_det = np.linalg.det(nparr_matmul)
print(nparr_det)


[[ 1  2  0 -1]
 [ 2  4  0 -2]
 [ 0  0  0  0]
 [-1 -2  0  1]]
0.0


This notebook covers the following topics:

1. Basic operations (multiplication, division, exponentiation)
2. Trigonometric functions (sine, cosine, tangent)
3. Inverse trigonometric functions (arcsine, arccosine, arctangent)
4. Hyperbolic functions (hyperbolic sine, hyperbolic cosine, hyperbolic tangent)
5. Inverse hyperbolic functions (inverse hyperbolic sine, inverse hyperbolic cosine, inverse hyperbolic tangent)
6. Statistical functions (mean, median, standard deviation, variance)
7. Random number generation (uniform, normal, integer)
8. Linear algebra (matrix multiplication, determinant)

In [34]:
# Trigonometric Functions
import numpy as np

# array of angles in radians
angles = np.array([0, 1, 2])
print("Angles:", angles)

# compute the sine of the angles
sine_values = np.sin(angles)
print("Sine values:", sine_values)

# compute the inverse sine of the angles
inverse_sine = np.arcsin(angles)
print("Inverse Sine values:", inverse_sine)

# Arithmetic Functions
first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the add() function
result2 = np.add(first_array, second_array)
print("Using the add() function:", result2)

# Rounding Functions
numbers = np.array([1.23456, 2.34567, 3.45678, 4.56789])

# round the array to two decimal places
rounded_array = np.round(numbers, 2)

print("Array after round():", rounded_array)

# Statistical Functions
array1 = np.array([1, 2, 3, 4, 5])

# calculate the median
median = np.median(array1)
print("Median is:", median)

# find the largest element
max = np.max(array1)
print("Largest element is", max)

Angles: [0 1 2]
Sine values: [0.         0.84147098 0.90929743]
Inverse Sine values: [0.         1.57079633        nan]
Using the add() function: [ 3  7 11 15]
Array after round(): [1.23 2.35 3.46 4.57]
Median is: 3.0
Largest element is 5


C:\Users\Admin\AppData\Local\Temp\ipykernel_24096\576588560.py:13: RuntimeWarning: invalid value encountered in arcsin
  inverse_sine = np.arcsin(angles)


This above code covers the following topics:

1. Trigonometric functions (sin, arcsin)
2. Arithmetic functions (add)
3. Rounding functions (round)
4. Statistical functions (median, max)