# **Aggregate Functions**
Aggregate functions are a set of functions in NumPy that perform operations on entire arrays or axes of arrays.

### Examples of Aggregate Functions

Some examples of aggregate functions include:

* `np.sum`: calculates the sum of an array or axis
* `np.mean`: calculates the mean of an array or axis
* `np.median`: calculates the median of an array or axis
* `np.std`: calculates the standard deviation of an array or axis
* `np.max`: calculates the maximum value of an array or axis
* `np.min`: calculates the minimum value of an array or axis

In [2]:
import numpy as np

# create an array
array = np.array([1, 2, 3, 4, 5])

# calculate the sum of the array
print(np.sum(array))  

# calculate the mean of the array
print(np.mean(array))  

# calculate the median of the array
print(np.median(array))  

# calculate the standard deviation of the array
print(np.std(array))  

# calculate the maximum value of the array
print(np.max(array)) 

# calculate the minimum value of the array
print(np.min(array))  

15
3.0
3.0
1.4142135623730951
5
1


In [6]:
# Import NumPy
import numpy as np

# Create a sample array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Max and Min
print("Max:", np.max(arr))
print("Min:", np.min(arr))

# Sum
print("Sum:", np.sum(arr))

# Mean
print("Mean:", np.mean(arr))

# Median
print("Median:", np.median(arr))

# Standard Deviation
print("Standard Deviation:", np.std(arr))

# Variance
print("Variance:", np.var(arr))

# Percentiles
print("25th Percentile:", np.percentile(arr, 25))
print("50th Percentile (Median):", np.percentile(arr, 50))
print("75th Percentile:", np.percentile(arr, 75))

# Argmax and Argmin
print("Index of Max:", np.argmax(arr))
print("Index of Min:", np.argmin(arr))

# Cumulative Sum
print("Cumulative Sum:", np.cumsum(arr))

# Cumulative Product
print("Cumulative Product:", np.cumprod(arr))

# Dot Product
arr2 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Dot Product:", np.dot(arr, arr2))

# Outer Product
print("Outer Product:\n", np.outer(arr, arr2))

Max: 10
Min: 1
Sum: 55
Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
25th Percentile: 3.25
50th Percentile (Median): 5.5
75th Percentile: 7.75
Index of Max: 9
Index of Min: 0
Cumulative Sum: [ 1  3  6 10 15 21 28 36 45 55]
Cumulative Product: [      1       2       6      24     120     720    5040   40320  362880
 3628800]
Dot Product: 3850
Outer Product:
 [[  10   20   30   40   50   60   70   80   90  100]
 [  20   40   60   80  100  120  140  160  180  200]
 [  30   60   90  120  150  180  210  240  270  300]
 [  40   80  120  160  200  240  280  320  360  400]
 [  50  100  150  200  250  300  350  400  450  500]
 [  60  120  180  240  300  360  420  480  540  600]
 [  70  140  210  280  350  420  490  560  630  700]
 [  80  160  240  320  400  480  560  640  720  800]
 [  90  180  270  360  450  540  630  720  810  900]
 [ 100  200  300  400  500  600  700  800  900 1000]]


This notebook covers the following NumPy aggregations:

1. `np.max` and `np.min`: find the maximum and minimum values in an array
2. `np.sum`: calculate the sum of all elements in an array
3. `np.mean`: calculate the mean (average) of all elements in an array
4. `np.median`: calculate the median of all elements in an array
5. `np.std` and `np.var`: calculate the standard deviation and variance of all elements in an array
6. `np.percentile`: calculate the nth percentile of all elements in an array
7. `np.argmax` and `np.argmin`: find the indices of the maximum and minimum values in an array
8. `np.cumsum` and `np.cumprod`: calculate the cumulative sum and product of all elements in an array
9. `np.dot`: calculate the dot product of two arrays
10. `np.outer`: calculate the outer product of two arrays