# **Broadcasting**

Broadcasting is a powerful feature in NumPy that allows you to perform operations on arrays with different shapes and sizes.

### What is Broadcasting?

Broadcasting is a set of rules that allows NumPy to perform operations on arrays with different shapes and sizes. It allows you to perform operations on arrays that would not be possible with traditional matrix multiplication.

### How Broadcasting Works

Broadcasting works by aligning the arrays along their axes and performing the operation element-wise. The rules of broadcasting are as follows:

1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
2. If the shape of the two arrays does not match in any dimension, the array with the size of one in that dimension is broadcasted to have the size of the other array in that dimension.
3. If the size of the two arrays does not match in any dimension, an error is raised.

In [4]:
import numpy as np

# create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([2])

# perform element-wise multiplication
print(array1 * array2) 

#In this example, array2 is broadcasted to have the same shape as array1 by repeating its value along the axis.
#The resulting array is the element-wise product of the two arrays.

[2 4 6]


## Broadcasting Rules
### Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.


In [9]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])

print(arr1 + arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


### Rule 2: If the shape of the two arrays does not match in any dimension, the array with the size of one in that dimension is broadcasted.

In [12]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)

[[5 7 9]]


### Rule 3: If the shape of the two arrays matches in all dimensions, the arrays are broadcasted element-wise.

In [15]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print(arr1 + arr2)

[[ 8 10 12]
 [14 16 18]]


## Broadcasting Examples
### Adding a scalar to an array

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr + 2)

[[3 4 5]
 [6 7 8]]


### Adding a 1D array to a 2D array

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

print(arr + arr2)

[[11 22 33]
 [14 25 36]]


### Adding a 2D array to a 2D array

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10, 20, 30], [40, 50, 60]])

print(arr + arr2)

[[11 22 33]
 [44 55 66]]
