# **Fancy Indexing in NumPy**=

Fancy indexing is a powerful feature in NumPy that allows you to access and manipulate arrays using integer arrays as indices.

### What is Fancy Indexing?

Fancy indexing is a way to access specific elements of an array using an integer array as an index. This allows you to select specific rows and columns of an array, or even specific elements of an array.

### Basic Fancy Indexing

Let's create a 2D array and use fancy indexing to access specific elements.


In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[0, 1])  
print(arr[1, 2])

2
6


### Fancy Indexing with Integer Arrays
Let's create an integer array and use it to index our original array.

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

index = np.array([0, 1, 2])

print(arr[index, 1])  

[2 5 8]


### Fancy Indexing with Multiple Integer Arrays
Let's create two integer arrays and use them to index our original array.

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

rows = np.array([0, 1, 2])
cols = np.array([0, 1, 0])

print(arr[rows, cols]) 

[1 5 7]


### Combined Fancy Indexing
Combined fancy indexing allows you to access specific elements of an array using multiple integer arrays as indices.

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

rows = np.array([0, 1, 2])
cols = np.array([0, 1, 0])

print(arr[rows, cols])  

[1 5 7]


### Modify Fancy Indexing
Let's use fancy indexing to modify specific elements of our original array.

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

rows = np.array([0, 1, 2])
cols = np.array([0, 1, 0])

arr[rows, cols] = 10

print(arr)  

[[10  2  3]
 [ 4 10  6]
 [10  8  9]]


### Boolean Fancy Indexing
Let's use a boolean array to index our original array.

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

mask = np.array([[True, False, True], [False, True, False], [True, False, True]])

print(arr[mask])  

[1 3 5 7 9]


## **Conclusion**
**Fancy indexing is a powerful feature in NumPy that allows you to access and manipulate arrays using integer arrays as indices. 
<br>It is a key concept in NumPy and is used extensively in scientific computing and data analysis.**