# **Sorting Arrays in NumPy**
Sorting arrays is an essential operation in data analysis and scientific computing. NumPy provides several functions to sort arrays, including `np.sort`, `np.argsort`, and `np.lexsort`.

### Sorting 1D Arrays

Let's create a 1D array and sort it using `np.sort`.

In [6]:
import numpy as np

arr = np.array([4, 2, 9, 6, 5, 1, 8, 3, 7])

print(np.sort(arr)) 

[1 2 3 4 5 6 7 8 9]


### Sorting 2D Arrays
Let's create a 2D array and sort it using np.sort.

In [8]:
arr = np.array([[4, 2, 9], [6, 5, 1], [8, 3, 7]])

print(np.sort(arr, axis=0))  # sorts along columns
print(np.sort(arr, axis=1))  # sorts along rows

[[4 2 1]
 [6 3 7]
 [8 5 9]]
[[2 4 9]
 [1 5 6]
 [3 7 8]]


### Sorting with np.argsort
np.argsort returns the indices of the sorted array.

In [11]:
arr = np.array([4, 2, 9, 6, 5, 1, 8, 3, 7])

indices = np.argsort(arr)
print(indices)  
print(arr[indices])  

[5 1 7 0 4 3 8 6 2]
[1 2 3 4 5 6 7 8 9]


### Sorting with np.lexsort
np.lexsort sorts arrays lexicographically (i.e., alphabetically).

In [14]:
arr = np.array([[4, 2, 9], [6, 5, 1], [8, 3, 7]])

print(np.lexsort(arr.T))  # sorts along columns

[1 2 0]


### Sorting with np.sort and kind Argument
np.sort allows you to specify the sorting algorithm using the kind argument.

In [17]:
arr = np.array([4, 2, 9, 6, 5, 1, 8, 3, 7])

print(np.sort(arr, kind='quicksort'))  # uses quicksort algorithm
print(np.sort(arr, kind='mergesort'))  # uses mergesort algorithm
print(np.sort(arr, kind='heapsort'))  # uses heapsort algorithm

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


# Fast Sorting: `np.sort` and `np.argsort`

`np.sort` returns a sorted copy of the input array, while `np.argsort` returns the indices of the sorted array.

```python


In [21]:
import numpy as np

arr = np.array([4, 2, 9, 6, 5, 1, 8, 3, 7])

print(np.sort(arr))  
print(np.argsort(arr))  

[1 2 3 4 5 6 7 8 9]
[5 1 7 0 4 3 8 6 2]


#### Time Complexity

| Function    | Complexity  | Algorithm     |
|-------------|-------------|---------------|
| `np.sort`   | O(n log n)  | Timsort       |
| `np.argsort`| O(n log n)  | Counting sort |

# Partial Sorting: np.partition
np.partition partially sorts the input array, selecting the k-th smallest element.

In [26]:
arr = np.array([4, 2, 9, 6, 5, 1, 8, 3, 7])

k = 3
print(np.partition(arr, k)) 

[1 2 3 4 5 6 8 9 7]


#### Time Complexity

 `np.partition`: O(n) using introselect algorithm